# Generated by Django 4.1.2 on 2022-11-21 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('ket', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodekrywn', models.CharField(max_length=8)),
                ('nama', models.CharField(max_length=50)),
                ('usia', models.IntegerField()),
                ('gaji', models.BigIntegerField()),
                ('tempat_lahir', models.CharField(blank=True, max_length=150)),
                ('waktu_posting', models.DateTimeField(auto_now_add=True)),
                ('jabatan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Karyawan.jabatan')),
            ],
        ),
    ]
